### ISSUE TITLE
node-vsl-vsl error

### ISSUE THREAD

**Issue by pigeon2049** [RSS3-Network/Node-Automated-Deployer#6]
docker-compose.yaml
```
services:
  node-vsl-core:
    command: --module=worker --worker.id=vsl-core
    container_name: node-vsl-core
    image: rss3/node:v0.5.9
    restart: unless-stopped
    volumes:
      - ${PWD}/config:/etc/rss3/node
  node-vsl-rss3:
    command: --module=worker --worker.id=vsl-rss3
    container_name: node-vsl-rss3
    image: rss3/node:v0.5.9
    restart: unless-stopped
    volumes:
      - ${PWD}/config:/etc/rss3/node
  node-vsl-vsl:
    command: --module=worker --worker.id=vsl-vsl
    container_name: node-vsl-vsl
    image: rss3/node:v0.5.9
    restart: unless-stopped
    volumes:
      - ${PWD}/config:/etc/rss3/node
  rss3_node_cockroachdb:
    command: start-single-node --cluster-name=node --insecure
    container_name: rss3_node_cockroachdb
    image: cockroachdb/cockroach:v23.2.5
    restart: unless-stopped
    volumes:
      - cockroachdb:/cockroach/cockroach-data
  rss3_node_core:
    command: --module=core
    container_name: rss3_node_core
    image: rss3/node:v0.5.9
    restart: unless-stopped
    volumes:
      - ${PWD}/config:/etc/rss3/node
  rss3_node_redis:
    container_name: rss3_node_redis
    image: redis:7-alpine
    restart: unless-stopped
volumes:
  cockroachdb:
```

error info:

node-vsl-vsl           | {"level":"fatal","ts":1717487803.1435127,"caller":"cmd/main.go:227","msg":"execute command","error":"new redis client: dial tcp: lookup redis on 127.0.0.11:53: no such host","stacktrace":"main.main\n\t/root/node/cmd/main.go:227\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271"}

**Comment by pigeon2049** [comment]
/rss3/config# cat config.yaml 
```
environment: production
type: beta
discovery:
  maintainer:
    evm_address: "xxxxxxx"
    signature: "xxxxxxx"
  server:
    global_indexer_endpoint: https://gi.rss3.io
    endpoint: https://xxxxxx
database:
  driver: cockroachdb
  partition: true
  uri: postgres://root@cockroachdb:26257/defaultdb
stream:
  enable: false
observability:
  opentelemetry:
    metrics:
      enable: false
      endpoint: 0.0.0.0:9090
    traces:
      enable: false
      insecure: true
      endpoint: localhost:4318
redis:
  endpoints:
    - redis:6379
  disable_cache: true
endpoints:
  crossbell:
    url: https://rpc.crossbell.io
  linea:
    url: https://rpc.linea.build
  vsl:
    url: https://rpc.rss3.io
component:
  decentralized:
    - id: vsl-core
      network: vsl
      worker: core
      endpoint: vsl
    - id: vsl-rss3
      network: vsl
      worker: rss3
      endpoint: vsl
    - id: vsl-vsl
      network: vsl
      worker: vsl
      endpoint: vsl
```

**Comment by HenryQW** [comment]
In your `config.yaml`, change these values:
```yaml
database:
  driver: cockroachdb
  partition: true
  uri: postgres://root@rss3_node_cockroachdb:26257/defaultdb
```

```yaml
redis:
  endpoints:
    - rss3_node_redis:6379
```
